In [1]:
import math

In [2]:
import numpy as np

In [ ]:
# Importing Library 
import numpy as np 
  


In [5]:
# inverse of 3X3 matrix 
arr = np.array([[1, 0.2, 0.5],  
                [0.2, 1, 0.8],  
                [0.5, 0.8, 1]]) 
inverse_array = np.linalg.inv(arr) 
print("Inverse array is ") 
print(inverse_array) 
print() 
  

Inverse array is 
[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]

