In [1]:
import math

In [3]:
import numpy as np

In [2]:
# Importing Library 
import numpy as np 
  


In [6]:
# inverse of 3X3 matrix 
arr = np.array([[1, 0.2, 0.5],  
                [0.2, 1, 0.8],  
                [0.5, 0.8, 1]]) 
inverse_array = np.linalg.inv(arr) 
print("Inverse array is ") 
print(inverse_array) 
print() 
  

Inverse array is 
[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]



In [8]:
# Displaying the Matrix 
# creating a 3X3 Numpy matrix 
arr = np.array([[1, 0.2, 0.5],  
                [0.2, 1, 0.8],  
                [0.5, 0.8, 1]]) 
print("Numpy Matrix is:") 
print(np.array) 

Numpy Matrix is:
<built-in function array>


In [9]:
# calculating the determinant of matrix 
det = np.linalg.det(arr) 
  
print("\nDeterminant of given 3X3 matrix:") 
print(int(det)) 


Determinant of given 3X3 matrix:
0


In [10]:

arr = np.array([[1, 0.2, 0.5],  
                [0.2, 1, 0.8],  
                [0.5, 0.8, 1]]) 
print("Original matrix:")
print(arr)


Original matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [12]:

result = np.linalg.qr(arr)
print("Decomposition of the said matrix:")
print(result) 


Decomposition of the said matrix:
QRResult(Q=array([[-0.88045091,  0.38615039, -0.27512557],
       [-0.17609018, -0.80507368, -0.566435  ],
       [-0.44022545, -0.4502713 ,  0.77682515]]), R=array([[-1.13578167, -0.70436073, -1.02132305],
       [ 0.        , -1.08806065, -0.90125505],
       [ 0.        ,  0.        ,  0.18611436]]))


In [14]:
#transforming a matrix
arr = np.array([[1, 0.2, 0.5],  
                [0.2, 1, 0.8],  
                [0.5, 0.8, 1]]) 
print(arr.flatten())

[1.  0.2 0.5 0.2 1.  0.8 0.5 0.8 1. ]


In [15]:
#question 5
m_list = [[4, 3], [-5, 9]]
A = np.array(m_list)

In [16]:
inv_A = np.linalg.inv(A)

print(inv_A)

[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [17]:
B = np.array([20, 26])
X = np.linalg.inv(A).dot(B)

print(X)

[2. 4.]


In [18]:
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
B = np.array([25, -10, -4])
X = np.linalg.inv(A).dot(B)

print(X)

[ 5.  3. -2.]


In [19]:
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
B = np.array([25, -10, -4])
X2 = np.linalg.solve(A,B)

print(X2)

[ 5.  3. -2.]


In [20]:
A = np.array([[20, 10], [17, 22]])
B = np.array([350, 500])
X = np.linalg.solve(A,B)

print(X)

[10. 15.]


In [21]:
#import linalg package of the SciPy module for the LU decomp
import scipy.linalg as linalg 
#import NumPy

In [22]:
A = np.array([[2., 1., 1.],
 [1., 3., 2.],
 [1., 0., 0.]]) 


In [23]:
#define B
B = np.array([4., 5., 6.]) 

In [24]:
#call the lu_factor function
LU = linalg.lu_factor(A) 